### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by frost-byte** [theminecoder/BukkitBugSnag#1]
I'm using code from another library that pretty much mirrors your implementation for integrating BugSnag into reporting errors from Bukkit.  I'm receiving an IllegalArgumentException when setting the pluginManagerField.  I don't know if this is because the bukkit api has changed, but I'm going to assume that the issue is related to setting the SimplePluginManager field called "pluginManager" to the LoggedPluginManager, which implements the PluginManager interface, but is not an instance of SimplePluginManager.

Do you see this issue with your code? Have you found an alternate method of integrating BugSnag with bukkit?

**Comment by theminecoder** [comment]
As far as I can tell spigot has changed the field type at some point to only accept the built in `SimplePluginManager` which is also final class which means it is impossible to replace using the current methods. If they change it to allow us to extend the class or go back to allowing anything that implements `PluginManager` into that field then it will work for you with no changes.

However if you use Paper (aka PaperSpigot) (once I get the command fix merged in) with the latest version of the code, which I highly recommend, everything should work out of the box.

**Comment by frost-byte** [comment]
Thanks for the response, I figured that might be the case. I've read about Paper. However, I'm helping the owner of my server with the plugin he wrote, so switching from spigot to paper would be his decision to make. (Which might be an easier proposition once 1.13 is released and supported)
